### PR TITLE
fix remote_plugin response sending

### PR DESCRIPTION
**Pull request by PolynomialDivision**
When you just use socket.send(...) you get an type error.
So use socket.send_unicode(...).

The error:
TypeError: unicode not allowed, use send_string

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Can confirm that I encountered the same bug and this PR fixes it. Thanks @PolynomialDivision

**Comment by mkassner** [comment]
@Tobias-Fischer @PolynomialDivision  what version of Python are you using 2 or 3?

**Comment by Tobias-Fischer** [comment]
Python 2.7.6 (default, Jun 22 2015, 17:58:13)

**Comment by mkassner** [comment]
@Tobias-Fischer on what request do you get this error?

**Comment by PolynomialDivision** [comment]
My Python version is:
    
    Python 2.7.11+

**Comment by Tobias-Fischer** [comment]
When using `pupil_remote`:
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/tobias/robot/pupil/pupil/pupil_src/shared_modules/pupil_remote.py", line 143, in thread_loop
    self.on_recv(remote_socket,ipc_pub)
  File "/home/tobias/robot/pupil/pupil/pupil_src/shared_modules/pupil_remote.py", line 190, in on_recv
    socket.send(response)
  File "zmq/backend/cython/socket.pyx", line 617, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:6625)
  File "zmq/backend/cython/socket.pyx", line 657, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:6300)
TypeError: unicode not allowed, use send_string
```

**Comment by mkassner** [comment]
alright. I found the error. IPC_SUB and PUB ports where saved as unicode objects. I fixed this with 0791544128c893a0e3c3a90b2cb3fe887c2b57f3

**Comment by Tobias-Fischer** [comment]
Working nicely. Thanks!

**Pull request closed without merging**
