### PR TITLE
add missing launcher_process.should_stop handling

### PR DESCRIPTION
**Pull request by bpinsard**
The code states that the launcher process should react to ` launcher_process.should_stop` though it seems not to be the case :
https://github.com/pupil-labs/pupil/blob/af660c38447cc6b199bd3eda292f4e4c769a0147/pupil_src/main.py#L124 

It assumes that closing children processes will lead to the launcher process exit.
Wrote that quickly, so would need feedback on implementation.

Thanks

### CODE REVIEW

**Review by papr — APPROVED** [review]

**Comment by papr** [comment]
@romanroibu please add this change to the Develop section of the release notes

**Comment by papr** [comment]
@bpinsard Thank you for your contribution!

**Comment by bpinsard** [comment]
@papr Sorry I made a typo in the code, pushed new changes to the branch but it's already merged.

**Comment by papr** [comment]
@bpinsard Could you please point me to the exact commit(s) that include(s) the typo fix?

**Comment by papr** [comment]
Fixed in #2071

**Pull request merged**
