### PR TITLE
Simpler Windows build using conda

### PR DESCRIPTION
**Pull request by cboulay**
New install instructions:

#### Developer Tools Requirements

If you don't already have them installed, you'll need git, conda (miniconda or anaconda), and MS Visual Studio 2017.

#### pupil dependencies

Get your Python environment ready. Install miniconda (or use Anaconda if you already have it installed), open an Anaconda Prompt and enter the following:

* `conda create -n pupil python=3.6 opencv boost eigen ceres-solver ffmpeg glfw glew`
* `conda activate pupil`
* `pip install pyzmq msgpack==0.5.6 pyopengl numpy pyaudio cython scipy psutil pyrealsense2`

There are some additional dependencies that are not found on pypi. The URLs below were correct at the time of writing but they may need to be updated. For the pupil derived packages, you can find them on their GitHub release pages. For pytorch, you can generate the pip command on the [pytorch website](https://pytorch.org/).

* `pip install --upgrade https://github.com/pupil-labs/pyglui/releases/download/v1.25/pyglui-1.25-cp36-cp36m-win_amd64.whl https://github.com/pupil-labs/PyAV/releases/download/v0.4.2/av-0.4.2.dev0-cp36-cp36m-win_amd64.whl https://github.com/pupil-labs/pyndsi/releases/download/v0.5/ndsi-0.5-cp36-cp36m-win_amd64.whl https://github.com/pupil-labs/pyuvc/releases/download/v0.13/uvc-0.13-cp36-cp36m-win_amd64.whl`
* `pip install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-win_amd64.whl torchvision`
* `pip install git+https://github.com/zeromq/pyre.git`
* `pip install git+https://github.com/pupil-labs/nslr`
* `pip install git+https://github.com/pupil-labs/nslr-hmm`

Finally we need to make sure conda has all the latest packages, because the ceres-solver fix is quite new:
* `conda update --all`

##### Get the source

The following steps assume you are still in an Anaconda Prompt with your pupil environment activated.

* `git clone https://github.com/pupil-labs/pupil.git`
* `cd pupil/pupil_src`

Note: If you want to test these changes before this is merged into pupil, you'll have to use Chad's branch:
* `git remote add -f cboulay https://github.com/cboulay/pupil.git`
* `git checkout cboulay/win_vcpkg_build`

##### Build the compiled modules

While we could rely on pupil_src/main.py to build the modules for us, if we build them directly we can get more useful error messages if the build fails.

* `cd shared_modules/pupil_detectors`
* `python setup.py install --install-lib ..\`
    * If this returns with an error related to `_ENABLE_EXTENDED_ALIGNED_STORAGE`, then follow the instructions [in this issue comment](https://github.com/pupil-labs/pupil/issues/1331#issuecomment-430418074) and run this command again.
    * If this returns an error related to `cannot open file 'boost_pythonPY_MAJOR_VERSIONPY_MINOR_VERSION` then it's because it is using an older bugged version of boost-python. Fix it with `conda upgrade boost -c conda-forge`
* `cd ../calibration_routines/optimization_calibration`
* `python setup.py install --install-lib ..\..\`
* `cd ../../cython_methods`
* `python setup.py build`
* `cd ../..` to get back to pupil_src

#### Running Pupil from source

Now, whenever you run pupil, these built modules will need to find the dlls to which they are linked. There are a few options:

* If you run from the Anaconda Prompt then everything should be taken care of for you.
    * run `run_capture.bat` (or `run_player.bat`)
* If you want to run inside an IDE then it'll need the path. Most IDEs can use the conda path, but an additional path item is needed:
    * The easiest thing to do is to first use an Anaconda prompt to run one of the batch files in pupil_src (e.g., `run_capture.bat`). This will modify the path. Cancel this (Ctrl+C). Then print the PATH to the screen with `echo %PATH%`. Copy the printed path to the clipboard (highlight then Enter) then paste this into your IDE.
    * In PyCharm it is necessary to use Ctrl+Shift+V to paste something from clipboard into the executable configuration environment variable.
    * PyCharm's debug mode prevents in-line cython building. See [here](https://youtrack.jetbrains.com/issue/PY-27833). If only running from PyCharm then this is no longer a problem with the merge of #1492.

## MacOS

I want to run pupil using a conda environment so I added build support for conda in MacOS as well. I think this might also fix some Mojave-specific build issues. The instructions are slightly changed from the developer docs; see below.

```
brew install libusb libjpeg-turbo portaudio glew glfw3 eigen ceres-solver

git clone --single-branch --branch build_fix_mac https://github.com/pupil-labs/libuvc
cd libuvc
mkdir build && cd build
cmake ..
make && make install

conda create -n pupil python=3.6 opencv scipy pyaudio boost
source activate pupil

pip install apriltag PyOpenGL pyzmq numexpr cython psutil msgpack==0.5.6 cysignals torch torchvision
pip install git+https://github.com/zeromq/pyre
pip install git+https://github.com/pupil-labs/PyAV
pip install git+https://github.com/pupil-labs/pyuvc
CFLAGS='-stdlib=libc++' pip install git+https://github.com/pupil-labs/pyndsi
CFLAGS='-stdlib=libc++' pip install git+https://github.com/pupil-labs/pyglui
CFLAGS='-stdlib=libc++' pip install git+https://github.com/pupil-labs/nslr
pip install git+https://github.com/pupil-labs/nslr-hmm
```

### CODE REVIEW

**Comment by mikkeyboi** [comment]
A step to add after successfully building the pupil_detectors and optimization_calibration:
- Download Microsoft Visual C++ 2010 Redistributable Package (x64) here: https://www.microsoft.com/en-us/download/details.aspx?id=14632

If not, you may get an error when importing pyuvc "ImportError: DLL load failed: The specified module could not be found". This triggered for me when executing run_capture.bat or main.py.
Tested to work on VS2017 and VS2019 (if using VS2019 make sure you download the MSVC toolset for 2017 otherwise you will get an error installing boost via vcpkg).

**Comment by cboulay** [comment]
Note to self:

The [deployment system](https://github.com/pupil-labs/pupil/tree/master/deployment) also needs to be updated to work with this.

**Comment by mikkeyboi** [comment]
With the newest version of vcpkg, 3D pupil detection failed to load the eye windows (although pupil_detectors, optimization_calibration, and cython_methods all built successfully.
One workaround was omitting `boost:x64-windows` from vcpkg install, recompile, running `conda install boost`, and then rebuilding all the modules (pupil_detectors, optimization_calibration, cython_methods).

This may be caused by the python (3.7) version of boost that vcpkg installs: `boost_python37-vc141-mt-x64-1_69`.

**Comment by cboulay** [comment]
There is now a [ceres-solver](https://github.com/conda-forge/ceres-solver-feedstock) in conda, but it's still [buggy](https://github.com/conda-forge/ceres-solver-feedstock/issues/3). As soon as that's resolved then the vcpkg step won't be needed and everything can be obtained with conda.

**Comment by cboulay** [comment]
conda ceres-solver has been fixed. I've updated the above install instructions. It's quite a bit simpler now! There is no longer a need for vcpkg. This also fixes the problem with the 3d-detector not working with the previous instructions.

**Comment by cboulay** [comment]
FYI: ceres-solver in conda also exists for Linux and Mac, so if you're happy using conda then chances are you can simplify the instructions for those platforms as well. Other than the windows-specific wheels from pupil and pytorch, almost everything else should work the same.

**Comment by papr** [comment]
@cboulay We are working on simplifying our dependencies (e.g. removing boost dependency) and started shipping some of our windows dependencies via pypi (e.g. https://github.com/pupil-labs/pupil-pthreads-win/). This is still work in progress, but the goal here is to simplify all dependencies to the point where a simple `pip install pupil-dependencies` does the trick. Still a long way to go though. In the meantime, your work is bridging the gap very well! Thank you again for your efforts and sharing your solutions with the community.

**Comment by papr** [comment]
We have taken further steps in regards to the simplification of the Windows setup by extracting all c++ dependencies into separate repositories (#1828) and providing wheels for them.

**Comment by cboulay** [comment]
Great! I'm uh.. not in the lab these days and I may not have access to the HMD with the pupil cameras inside for a little while... so please close this PR if you think it's no longer needed.

**Comment by papr** [comment]
Yeah, I fully understand your situation. I hope you and your family are and stay healthy! The access to our VR setup in our office is also very limited at the moment. We greatly appreciate the effort that you put into this PR, giving Windows developers an alternative to the official (previously quite painful) setup instructions. As the instructions point to your fork, they keep their validity. But as this fork has not been updated for a while, I would prefer to close this PR as we would like to encourage users to use the most recent version of Capture.

**Pull request closed without merging**
