### PR TITLE
Timebased seeking

### PR DESCRIPTION
**Pull request by papr**
Convert from index-based to time-based drawing:
- [ ] Offline calibration ranges
- [ ] Offline surface tacker cache bars

Requires `pyglui v1.16`, https://github.com/pupil-labs/pyglui/pull/94

### CODE REVIEW

**Comment by mkassner** [comment]
This open issues here? @papr should I merge of wait?

**Comment by papr** [comment]
I would suggest waiting.

**Comment by mkassner** [comment]
I ll fix  "Offline calibration ranges" and will "Offline surface tacker cache bars" be a know issue until fixed

**Comment by papr** [comment]
Both are fixed with direct commits into master

**Pull request merged**
