### PR TITLE
current frame feedback on dragging trim marks

### PR DESCRIPTION
**Pull request by cpicanco**
On Trim marks. Allow one to see what is the current frame when in dragging mode.

### CODE REVIEW

**Comment by mkassner** [comment]
this is a nice feature.  but we should use pyfontstash to render this info. I can help with implementation.

**Comment by cpicanco** [comment]
Good! I tried to make the frame number follow the x cursor (similar to youtube video previews), but since some recordings I had have 10.000 frames I found a little bit difficult to adjust the size with the opencv stuff. But for me a fixed position is working, what do you think?

**Comment by cpicanco** [comment]
I am having difficulties trying to implement the gl stuff to auto-resize the font and keep its aspect ratio. There is an example in the pupil code already that I was missing?

**Comment by mkassner** [comment]
I think I have a good solution for this using the new logger visuals. I'll close this for now.

**Pull request closed without merging**
