### PR TITLE
 Make scene video recording optional 

### PR DESCRIPTION
**Pull request by papr**
Add UI toggle to Recorder menu to disable scene/world video recording in Pupil Capture. Recording scene video remains the default behavior.

### CODE REVIEW

**Review by N-M-T — APPROVED** [review]
The functionality works as expected. Tested with and without calibration.

**Review by romanroibu — APPROVED** [review]

**Comment by xcwangbcp** [comment]
Hi, i want to use the pupil core work on a screen. no need world camer. i set the record_world=False, and tested with the code in the master branch, it does not work for calibration, any thing else need to modify?

**Comment by N-M-T** [comment]
> Hi, i want to use the pupil core work on a screen. no need world camer. i set the record_world=False, and tested with the code in the master branch, it does not work for calibration, any thing else need to modify?

Hi @xcwangbcp. You'll need to use the world camera in order to calibrate Core. For screen-based work, you'll also need April Tag markers affixed to your screen. Further details here: https://docs.pupil-labs.com/core/software/pupil-capture/#surface-tracking

**Comment by xcwangbcp** [comment]
> > Hi, i want to use the pupil core work on a screen. no need world camer. i set the record_world=False, and tested with the code in the master branch, it does not work for calibration, any thing else need to modify?
> 
> Hi @xcwangbcp. You'll need to use the world camera in order to calibrate Core. For screen-based work, you'll also need April Tag markers affixed to your screen. Further details here: https://docs.pupil-labs.com/core/software/pupil-capture/#surface-tracking

My expression may have something wrong. I'll rephrase the purpose: Using only two or one eye camera and Pupil Capture, can it do eye tracking on the designated screen, like eyelink?

**Comment by mikelgg93** [comment]
Hi @xcwangbcp  👋🏽 ! Pupil Core is a **wearable** eye tracker that moves with your head and does not have a fixed reference to screen coordinates like a **remote** eye tracker like the one you mention. We employ the scene camera and markers to estimate this reference/translation even as you rotate, tilt, or move your head. 

To achieve eye tracking on a designated screen **without** using a scene camera, the eye tracker would need to be stationary,  which is contrary to the purpose of a wearable eye tracker.

You could affix/arrest Pupil Core's position in space and modify the code to achieve that aim, but for that specific purpose, there are many remote eye trackers on the market that do this out of the box.

**Pull request merged**
