### PR TITLE
Organized player plugin list into visualization, analysis, and other

### PR DESCRIPTION
**Pull request by snleu**

### CODE REVIEW

**Comment by papr** [comment]
Nice idea! Could we have something similar for Capture? No idea about suitable categories though..

**Comment by willpatera** [comment]
@snleu - I think one quick fix might be to simply sort the plugins by alphabetical order and name them appropriately (if not already). Many of the visualization plugins are already prefixed with `vis`.

**Comment by mkassner** [comment]
I like this PR. I m good with merging unless somebody objects. The current list is to long for sure.

**Comment by willpatera** [comment]
Ok, but please also sort alphabetically even if in separate lists before merging.

**Comment by cpicanco** [comment]
related to #246

**Comment by cpicanco** [comment]
PS.: A tab UI element would be great...

**Comment by papr** [comment]
@cpicanco Do you have a specific use case for the tab ui in the current context? I would suggest to create an issue for that over at pupil/pyglui :)

**Comment by cpicanco** [comment]
Please see: https://github.com/pupil-labs/pyglui/issues/42

**Pull request merged**
