### PR TITLE
Fix eye overlay plugin

### LINKED ISSUE #738: Minor issue - Frame scrubber problem in Pupil Player
When I drag the frame scrubber in Pupil Player, when I release white ball, it jumps ahead to a different part of the video. As near as I can tell, this is proportional to where I am trying to go in the video, e.g. if I am scrubbing to a point early in the video, it jumps ahead a small amount. If I am scrolling near the end of the video, it jumps ahead a large amount. 

It looks as though when you try to scroll to a particular part of a video it adds the frame number to the current frame upon release of the mouse button (i.e, dragging the white ball to frame#300 jumps to frame#600 upon release). 

Not a major issue, just annoying :)

### PR DESCRIPTION
**Pull request by papr**
Fixes #738

### CODE REVIEW

**Comment by mkassner** [comment]
@papr  2d pupil data also has an ellipse. this fix should not be required. Have you tested running a normal 2d recording without this fix?

 @cpicanco pupil_data file had data from a  very old 2d pupil detector written in python.

**Comment by papr** [comment]
@mkassner No, I did not test it with 2d data. I assumed @cpicanco data to be up-to-date. But this means we should change the warning to something containing the words "deprecated data format".

**Comment by mkassner** [comment]
@papr  I dont want to add a warning like this. We need to assume that the data is conform with what we expect at the version. Glue and fixing like this belongs in player methods.  We cant start proving code against non-confirm pupil_data.

**Comment by papr** [comment]
Ok, are you suggesting to remove the `try-except` fix completely? Player-methods will only be called on upgrading the recording. It is very likely that most of the recordings are already upgraded to the point where player methods are not called anymore. And even if they were called, there would be no way to generate the correct ellipses for the deprecated data.

**Comment by mkassner** [comment]
Yes this is what I am suggesting. Just remove your fix. 

If @cpicanco  confirms that his recording was made on a unmodified version of Pupil Im happy to invest time to add a fix in player methods.

**Comment by mkassner** [comment]
the renaming part should remain in this PR

**Comment by mkassner** [comment]
I just confirmed the current master branch eye visulizer for player works just fine with 2d and 3d data.

@papr please do not fix problems without reproducing the error first. Please make a new PR that contains only the renaming commit.

**Comment by cpicanco** [comment]
I can confirm that I was using an unmodified version of an old pupil 2d
capture. My modifications are being done in pupil player plugins. I do
remember that ellipese data was added after 4.x capture version by requests
from other pupil community members. I would suggest to leave any
redetection task for the offline detector. Is breaking support for 4.x data
and older in your mind?

**Comment by mkassner** [comment]
In this case I would say we add a converter in player_methods to add dummy data.

**Comment by papr** [comment]
Or we generate circles from `norm_pos` and `diameter`. That would not be total dummy data at least.

**Comment by mkassner** [comment]
@cpicanco alright this info helps a lot! Let add this to the conversion step in player_methods.

**Pull request closed without merging**
