### PR TITLE
Updating close button locations

### PR DESCRIPTION
**Pull request by cpicanco**
#231 
First commit updates vis_circle.py

### CODE REVIEW

**Comment by mkassner** [comment]
For the plugins with info text. Should we consider having the close button as the first ui element below the info text?

**Comment by cpicanco** [comment]
Honestly, I think the close button is so basic that it should be included in the plugin bar.  Right now, when you open a plugin, the close button will always be at sight, because plugins will load in a "minimized" state. Closing and opening a plugin becomes more agile this way, with a fixed position and with the close button always at sight.

**Comment by willpatera** [comment]
I think for now the close button should just be the first UI element, followed by info text, this way the pattern will always be the same. 

For the next milestone (v7.0), I agree with @cpicanco -- making the close button as a simple `X` as part of the plugin title bar would be nice (see sketch with 2 options below). 

pyglui_close_menu-01

Option 1 - keep collapse button. 
Option 2 - remove collapse button -- only click on title of plugin to collapse the menu. 

I will migrate this to [pyglui repo](https://github.com/pupil-labs/pyglui) -- as a feature request as it is most appropriate in that context.

**Comment by cpicanco** [comment]
So, I think this can be merged! :smile:

**Comment by mkassner** [comment]
done!

**Pull request merged**
