### PR TITLE
Fixes for OpenCV3 using ROS

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Hi,
This is (re-)introducing the ability to use OpenCV3 provided by ROS. This is only used if OpenCV3 is not found in the default path. I've extended it a little so is searches through all ROS distributions which provide OpenCV3. It will also be easy to extend this for other operating systems etc.

Best,
Tobias

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Does the PR look okay to you guys?

**Comment by willpatera** [comment]
Hi @Tobias-Fischer - I am testing this now.

**Comment by willpatera** [comment]
@Tobias-Fischer - I will merge this - but in order to facilitate a merge into master, I have made a clean branch [`opencv3_rebase`](https://github.com/pupil-labs/pupil/tree/opencv3_rebase) that shows clearly the changes that need to be made. I have `@` mentioned you in some commit messages and will also reference your contributions in the new PR.

**Comment by Tobias-Fischer** [comment]
Sounds good, thanks!

**Pull request merged**
