### PR TITLE
Update wide-angle lens intrinsics

### PR DESCRIPTION
**Pull request by romanroibu**
This PR updates the default Pupil Cam1 ID2 intrinsics with new wide-angle intrinsics.

---

[ClickUp Task](https://app.clickup.com/t/8rnqgz)

### CODE REVIEW

**Review by papr — APPROVED** [review]
Values look correct. @romanroibu Feel to merge after the sanity-check (visually inspecting straight edges in the undistorted preview provided by the camera intrinsics estimation plugin)

**Comment by papr** [comment]
Actually, doing the sanity check with my own headset showed that the new intrinsics might not generalize as well as I thought. I am putting this into draft until this has been discussed.

**Comment by papr** [comment]
Actually, the issue was that I had a custom – but badly fitted – intrinsics file in my `capture_settings` folder. After deleting it, the undistortion worked as expected. I will reopen again. @romanroibu Feel free to merge after your own check.

**Comment by pfaion** [comment]
@romanroibu why did you add the `"resolution"` keys?

**Review by pfaion — CHANGES_REQUESTED** [review]
@romanroibu why did you add the `"resolution"` keys?
I think this is just duplicated data, as the key in the dictionary is already the resolution.

**Review by pfaion — APPROVED** [review]

**Pull request merged**
