### PR TITLE
Problem: OS X might start sleeping during recording

### PR DESCRIPTION
**Pull request by papr**
See feature request pupil-labs/pupil#414

Solution: Use built-in `caffeinate` utility to prevent this behaviour.

State:
- [x] Support OS X
- [x] Start/stop `caffeinate`
- [ ] Support other platforms

### CODE REVIEW

**Comment by mkassner** [comment]
I don't think we should use `caffeinate `. Neither is it required to write a plugin. 

1) If we want Pupil Capture to prevent idle sleep, it should prevent it when started not just during recording. 
2) The proper way of doing this for mac is documented here: https://developer.apple.com/library/mac/qa/qa1340/_index.html

**Comment by papr** [comment]
Use of `caffeinate` as discussed. @mkassner Please review.

**Comment by papr** [comment]
Ready to merge.

**Comment by papr** [comment]
Fixes #415

**Pull request merged**
