### PR TITLE
Opencv3 rebase

### PR DESCRIPTION
**Pull request by willpatera**
## Overview

Granular commits ported from the [`opencv3`](https://github.com/pupil-labs/pupil/tree/opencv3) branch and rebased on the current `master`. 

This branch branch integrates work from @Tobias-Fischer's commits to the `opencv3` branch see PRs - #488, #393. 
### Tests
- [x] Pupil Capture - All Cython libs compile on macOS `10.12` with opencv3 (and no other versions of opencv
- [x] Pupil Player - All plugins working with `opencv3`
- [x] Test on Linux (Ubuntu) with ROS (@Tobias-Fischer - you have already done this for ROS so you can probably check this off)
- [ ] Test on Linux with `opencv3` without ROS
### Needs review
- [ ] review changes to [`vis_light_points`](https://github.com/pupil-labs/pupil/commit/5d2643c9c827cb3812c1f2f4a503b1f01b2295c4)
- [ ] review cython `setup.py` files [here](https://github.com/pupil-labs/pupil/commit/fbdb634d7cb60241c6faf56145fe4f03695764e5) and [here](https://github.com/pupil-labs/pupil/commit/fbdb634d7cb60241c6faf56145fe4f03695764e5) -consider changing :
  
  ``` python
  if os.path.isfile(os.path.join(opencv_library_dir,libopencv_core.so)):
    pass
  else:
    ... 
  ```
  
  or changing to `try` `except` instead of `if (not ...` statement? Also use `os.path.join` to avoid future errors. 
### Roadblocks

Wait until the `opencv3` install process is mature for macOS. This will happen when `brew install opecv3` pulls changes from `brew install opencv3 --HEAD --with-contrib`.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @willpatera,
I can confirm that this branch is working fine on Linux with ROS.

Best,
Tobias
PS: I don't have edit access to your post, so please tick the item :).

**Comment by Tobias-Fischer** [comment]
Regarding OpenCV3 without ROS, I suggest using an environment variable pointing to the install directory, and checking against it in the `setup.py`:
```
if(os.environ.get('OpenCV_DIR')):
    opencv_library_dir = os.environ.get('OpenCV_DIR') + '/lib'
    opencv_include_dir = os.environ.get('OpenCV_DIR') + '/include'
```
Pretty simple change, and it does the job.

Best,
Tobias

**Comment by willpatera** [comment]
@Tobias-Fischer - thanks for the update and suggestion. I have ticked the box for `test on Ubuntu with ROS`.

I will make this change you suggest in `setup.py` and commit it to this branch.

**Comment by willpatera** [comment]
@Tobias-Fischer - I am going to close this PR because changes will happen in #570 (soon the master branch will be Python `v3.0` and OpenCV `v3.0`

**Pull request closed without merging**
