### PR TITLE
Pupil remote

### PR DESCRIPTION
**Pull request by mkassner**
This PR adds  `Pupil Remote`" 

- Motivated by #352 and conversations with pupil community members ( @papr , @cpicanco  and others ).
- A new plugin that offers a simple way of controlling pupil from non python environments like matlab 
- It handles requests in a separate thread to reduce latency. (As opposed to the initial version posted in  #352)

### CODE REVIEW

**Comment by mkassner** [comment]
@willpatera  please review and test.

**Comment by willpatera** [comment]
Added pupil-helpers code for pupil remote here: https://github.com/pupil-labs/pupil-helpers/blob/master/pupil_remote/pupil_remote_controls.py

**Comment by cpicanco** [comment]
@mkassner ,  @willpatera , may ask why:

```
raw_time = self.g_pool.capture.get_now()
self.g_pool.timebase.value = raw_time-target
response = 'Timesync successful.'
```
Instead of:
```
response = str(self.g_pool.capture.get_timestamp())
```

**Comment by mkassner** [comment]
Hi,

do you mean why this:
```python
raw_time = self.g_pool.capture.get_now()
self.g_pool.timebase.value = raw_time-target
```

or 

why the response : 'Timesync successful.'

?

**Comment by cpicanco** [comment]
Why this:

    raw_time = self.g_pool.capture.get_now()
    self.g_pool.timebase.value = raw_time-target

I mean why syncing if you can ask for the altered timestamps directly??

**Comment by mkassner** [comment]
Nice Idea. Ill add this as well. I guess its better to sync once instead of getting the time over tcp a bunch of times.

**Comment by cpicanco** [comment]
PS.: For some reason pascal precision is 1e-9 and pupil is 1e-7.
___

Hi,

This documents time offsets in my specific case using `g_pool.capture.get_timestamp()` and the following in pascal:

``` pascal
function GetCustomTick: Extended;
var
  tp: timespec;
  a, b : Extended;
begin
  clock_gettime(CLOCK_MONOTONIC, @tp);
  a := tp.tv_sec;
  b := tp.tv_nsec * 1e-9;
  Result := a+b;
  //FloatToStrF(Result, ffFixed, 0, 9);
end; 
```

> TimeReceived (Pascal) : TimeSent (Pupil) : TimeRequested (Pascal)

```txt
39399.624754201 : ('39399.6222907', 'S:39399.621943400')
39401.041685925 : ('39401.0407598', '*R:39401.040048224')
39401.179102830 : ('39401.1788807', 'R:39401.178532624')
39401.326831221 : ('39401.3165072', 'C:39401.315771846')
39401.336338662 : ('39401.3358917', 'R:39401.325945041')
39401.447637273 : ('39401.4474269', 'R:39401.447074889')
39401.582897117 : ('39401.5826541', 'R:39401.582025743')
39401.719894399 : ('39401.7097553', 'C:39401.709366398')
39401.721674303 : ('39401.7213899', 'R:39401.719491539')
39401.825342320 : ('39401.8250462', 'R:39401.824661481')
39401.972066354 : ('39401.9716699', 'R:39401.963612718')
39402.121547828 : ('39402.1113093', 'C:39402.110928191')
39402.123114848 : ('39402.1220951', 'R:39402.121054730')
39402.246935366 : ('39402.2467166', 'R:39402.246213738')
39402.383571415 : ('39402.3832856', 'R:39402.382871020')
39402.597558551 : ('39402.587113', 'C:39402.586639143')
39402.609403251 : ('39402.6091096', 'R:39402.596789429')
39402.689033206 : ('39402.6888295', 'R:39402.688409639')
39402.811744322 : ('39402.8113884', 'R:39402.799585324')
39402.924677561 : ('39402.9109027', 'C:39402.910082405')
39402.926598550 : ('39402.926403', 'R:39402.921105741')
39403.150376694 : ('39403.1499898', 'R:39403.149620144')
39403.256768905 : ('39403.2565602', 'R:39403.256149249')
39403.361461393 : ('39403.3513636', 'C:39403.350918305')
39403.363096301 : ('39403.3628242', 'R:39403.361053504')
39403.458697059 : ('39403.4584847', 'R:39403.458122382')
39403.683108547 : ('39403.68273', 'R:39403.679877844')
39403.802672494 : ('39403.7923537', 'C:39403.791845560')
39403.804815028 : ('39403.8031701', 'R:39403.801992772')
39403.903846801 : ('39403.9032855', 'R:39403.901653700')
39404.026527186 : ('39404.0263101', 'R:39404.025975419')
39404.160810332 : ('39404.1525537', 'C:39404.146844331')
39404.166003092 : ('39404.1658022', 'R:39404.156970310')
39404.394421949 : ('39404.3933008', 'R:39404.392816096')
39404.520468813 : ('39404.5202386', 'R:39404.519826528')
39404.670188316 : ('39404.6601724', 'C:39404.659619525')
39404.671922123 : ('39404.6705912', 'R:39404.669789367')
39404.859977866 : ('39404.8576632', 'R:39404.857122644')
39405.142366001 : ('39405.1421012', 'R:39405.141659180')
39405.276450231 : ('39405.2652604', 'C:39405.264953075')
39405.279150120 : ('39405.2772062', 'R:39405.275051675')
39405.876602754 : ('39405.8763295', 'R:39405.875813797')
39406.491135035 : ('39406.4907596', 'R:39406.487942327')
39406.837945018 : ('39406.8312073', 'C:39406.827354716')
39406.839945070 : ('39406.8397531', 'R:39406.837482372')
39406.953804441 : ('39406.9535055', 'R:39406.952720183')
39407.096664706 : ('39407.0963093', 'R:39407.092576040')
39407.279893393 : ('39407.2692048', 'C:39407.268800214')
39407.281381907 : ('39407.2803482', 'R:39407.279492768')
39407.387887825 : ('39407.3876152', 'R:39407.387256994')
39407.524513258 : ('39407.5228021', 'R:39407.522348374')
39407.741069255 : ('39407.7324631', 'C:39407.730106545')
39407.744950904 : ('39407.7446947', 'R:39407.740248728')
39407.898656542 : ('39407.8983339', 'R:39407.892758916')
39408.048536406 : ('39408.0483056', 'R:39408.047957260')
39408.212680925 : ('39408.2024264', 'C:39408.202097886')
39408.213890902 : ('39408.2131634', 'R:39408.212212970')
39408.511116412 : ('39408.5108309', 'R:39408.510295047')
39408.971731008 : ('39408.9714952', 'R:39408.971178403')
39409.142580828 : ('39409.130897', 'C:39409.129735124')
39409.144624463 : ('39409.1443769', 'R:39409.141269996')
39409.212042338 : ('39409.2117222', 'R:39409.211130455')
39409.453707804 : ('39409.4527224', 'R:39409.451980702')
39409.767120633 : ('39409.756805', 'C:39409.756475014')
39409.779039088 : ('39409.7786728', 'R:39409.766596244')
39409.841258337 : ('39409.8405079', 'R:39409.837582588')
39409.924535824 : ('39409.9242405', 'R:39409.923859455')
39410.104064456 : ('39410.0932669', 'C:39410.092957309')
39410.112245980 : ('39410.1112866', 'R:39410.103127430')
39410.179084709 : ('39410.1786682', 'R:39410.169260735')
39410.347375725 : ('39410.3470642', 'R:39410.346247605')
39410.448563163 : ('39410.4351347', 'C:39410.434619232')
39410.449232548 : ('39410.4490638', 'R:39410.448084872')
39410.511080506 : ('39410.5106975', 'R:39410.504699561')
39410.626554111 : ('39410.6260878', '2b:39410.625687487')
39410.686033799 : ('39410.6854742', '*R:39410.685078613')
39410.801227469 : ('39410.795248', 'C:39410.790658958')
39410.803629822 : ('39410.8031851', 'R:39410.800776556')
39410.870082454 : ('39410.8698193', 'R:39410.869488781')
39410.971434165 : ('39410.9710578', 'R:39410.963850786')
39411.058345774 : ('39411.0474775', 'C:39411.047165430')
39411.061538761 : ('39411.0608473', 'R:39411.057401484')
39411.138831737 : ('39411.138497', 'R:39411.137968466')
39411.235985825 : ('39411.2357687', 'R:39411.233113003')
39411.414197480 : ('39411.4038078', 'C:39411.403508837')
39411.415774557 : ('39411.415577', 'R:39411.413764726')
39411.582380098 : ('39411.5821569', 'R:39411.581821905')
39411.686876744 : ('39411.6866524', 'R:39411.686316874')
39411.892637935 : ('39411.878066', 'C:39411.877749155')
39411.900599310 : ('39411.9002627', 'R:39411.887867592')
39411.964744856 : ('39411.9643322', 'R:39411.957844551')
39412.135796385 : ('39412.1354541', 'R:39412.132924122')
39412.326322929 : ('39412.3157597', 'C:39412.315474763')
39412.338263176 : ('39412.3379198', 'R:39412.325694334')
39412.502210176 : ('39412.5018973', 'R:39412.496318977')
39412.594933642 : ('39412.594621', 'R:39412.594227100')
39412.689340906 : ('39412.6791415', 'C:39412.678787761')
39412.691060744 : ('39412.6908219', 'R:39412.688927430')
39412.772258557 : ('39412.7705532', 'R:39412.767050711')
39412.948275993 : ('39412.9478337', 'R:39412.947286164')
39413.052643567 : ('39413.0430051', 'C:39413.041997110')
39413.054425706 : ('39413.0541854', 'R:39413.052196845')
39413.127084115 : ('39413.1258247', 'R:39413.125191343')
39413.299848219 : ('39413.299518', 'R:39413.298996960')
39413.499762911 : ('39413.488851', 'C:39413.488357948')
39413.501841467 : ('39413.5002501', 'R:39413.499351111')
39413.657436525 : ('39413.6572234', 'R:39413.656803180')
39413.831442734 : ('39413.8312184', 'R:39413.830887055')
39414.028459180 : ('39414.0192241', 'C:39414.017440315')
39414.031559973 : ('39414.0294621', 'R:39414.027759623')
39414.203066327 : ('39414.2026989', 'R:39414.202232390')
39414.392629583 : ('39414.3923974', 'R:39414.392044011')
39414.504079615 : ('39414.4938341', 'C:39414.493526749')
39414.506179125 : ('39414.5059509', 'R:39414.503650494')
39414.689100219 : ('39414.6887767', 'R:39414.677833827')
39414.771498510 : ('39414.7712725', 'R:39414.770928584')
39414.968293971 : ('39414.9597576', 'C:39414.957710373')
39414.969531047 : ('39414.9687575', 'R:39414.967843337')
39415.039226395 : ('39415.0389875', 'R:39415.038494710')
39415.133908845 : ('39415.1336809', 'R:39415.133337242')
39415.313521290 : ('39415.3028642', 'C:39415.302414142')
39415.325655144 : ('39415.3253286', 'R:39415.312824247')
39415.401188890 : ('39415.4008682', 'R:39415.400249628')
39415.589955925 : ('39415.5896405', 'R:39415.588355380')
39415.696387808 : ('39415.6907858', 'C:39415.684936189')
39415.697085968 : ('39415.696901', 'R:39415.695439047')
39415.861699559 : ('39415.861288', 'R:39415.855165236')
39416.041749507 : ('39416.0415221', 'R:39416.041180697')
39416.234066292 : ('39416.2273602', 'C:39416.222394805')
39416.238037062 : ('39416.2345591', 'R:39416.233484631')
39416.416770311 : ('39416.4162484', 'R:39416.415278164')
39416.605461914 : ('39416.6044849', 'R:39416.603803539')
39416.814758608 : ('39416.8045547', 'C:39416.804229768')
39416.816396310 : ('39416.8161896', 'R:39416.814352675')
39416.905043681 : ('39416.9045176', 'R:39416.904146325')
39416.978300792 : ('39416.9780974', 'R:39416.977653199')
39417.173816990 : ('39417.1631401', 'C:39417.162628824')
39417.175507494 : ('39417.1752924', 'R:39417.173421953')
39417.252316591 : ('39417.2518302', 'R:39417.251532662')
39417.331895979 : ('39417.3315825', 'R:39417.322920749')
39417.518228532 : ('39417.5080352', 'C:39417.507701369')
39417.519910934 : ('39417.5196606', 'R:39417.517818408')
39417.679043449 : ('39417.6788135', 'R:39417.678460671')
39417.871570884 : ('39417.8712281', 'R:39417.859689585')
39417.969472861 : ('39417.9593391', 'C:39417.958804613')
39417.971639980 : ('39417.9714441', 'R:39417.968928637')
39418.181672830 : ('39418.1812026', 'R:39418.180650872')
39418.351292837 : ('39418.3510758', 'R:39418.350742746')
39418.528742633 : ('39418.5183898', 'C:39418.518069356')
39418.539303322 : ('39418.5389407', 'R:39418.528186396')
39418.713867724 : ('39418.713618', 'R:39418.712747426')
39418.807361708 : ('39418.807015', 'R:39418.799914944')
39418.911126948 : ('39418.9061532', 'C:39418.900236875')
39418.911965355 : ('39418.911784', 'R:39418.910629100')
39419.071589572 : ('39419.0712445', 'R:39419.066945786')
39419.148487790 : ('39419.1482665', 'R:39419.147787953')
39419.244396979 : ('39419.2400868', 'C:39419.232866018')
39419.245091507 : ('39419.244885', 'R:39419.243014906')
39419.320081029 : ('39419.3198243', 'R:39419.319489311')
39419.483246056 : ('39419.4830064', 'R:39419.482625003')
39419.627202872 : ('39419.6260882', '1b:39419.625692845')
39419.726541401 : ('39419.7161148', 'C:39419.715769225')
39419.729961521 : ('39419.7296735', '*R:39419.725951638')
39419.827614295 : ('39419.8272919', 'R:39419.824506238')
39419.996578886 : ('39419.996245', 'R:39419.987532415')
39420.161052510 : ('39420.1500725', 'C:39420.149748682')
39420.164790280 : ('39420.1645115', 'R:39420.159916568')
39420.331115608 : ('39420.3307647', 'R:39420.325394827')
39420.423690725 : ('39420.4230448', 'R:39420.422629655')
39420.596569373 : ('39420.5856986', 'C:39420.585357738')
39420.603050056 : ('39420.5998403', 'R:39420.595530932')
39420.770851885 : ('39420.7665699', 'R:39420.765943529')
39420.932590698 : ('39420.932249', 'R:39420.928554554')
39421.119205979 : ('39421.1091063', 'C:39421.108551700')
39421.120882794 : ('39421.1196575', 'R:39421.118791944')
39421.282153373 : ('39421.2819282', 'R:39421.281588754')
39421.382051212 : ('39421.3818238', 'R:39421.381457817')
39421.483214624 : ('39421.4729241', 'C:39421.472485471')
39421.485311340 : ('39421.4851381', 'R:39421.482700013')
39421.561983263 : ('39421.5617553', 'R:39421.561466138')
39421.660855234 : ('39421.6601722', 'R:39421.659591058')
39421.761366582 : ('39421.7507193', 'C:39421.750405548')
39421.764600638 : ('39421.7621167', 'R:39421.760534042')
39421.841794156 : ('39421.8415181', 'R:39421.840811870')
39421.942514757 : ('39421.9395911', 'R:39421.930062414')
39422.031807208 : ('39422.0211999', 'C:39422.020863495')
39422.039908271 : ('39422.0396149', 'R:39422.031030822')
39422.111242997 : ('39422.1109337', 'R:39422.105922562')
39422.209577728 : ('39422.2092084', 'R:39422.198273340')
39422.296516995 : ('39422.2857993', 'C:39422.285483602')
39422.310328501 : ('39422.3098902', 'R:39422.295616287')
39422.444969249 : ('39422.4447508', 'R:39422.444214095')
39422.607718285 : ('39422.6073339', 'R:39422.605073713')
39422.806330806 : ('39422.7956318', 'C:39422.795321440')
39422.810144567 : ('39422.8098632', 'R:39422.805464462')
39422.886962883 : ('39422.8866645', 'R:39422.886289308')
39422.979933876 : ('39422.9795581', 'R:39422.973391730')
39423.168373203 : ('39423.1577427', 'C:39423.157426417')
39423.180908241 : ('39423.1805442', 'R:39423.167563572')
39423.337776694 : ('39423.3365581', 'R:39423.335973881')
39423.498168077 : ('39423.4979437', 'R:39423.497621897')
39423.685815094 : ('39423.6806779', 'C:39423.675075884')
39423.688120784 : ('39423.6863353', 'R:39423.685249917')
39423.927177996 : ('39423.9269542', 'R:39423.926608907')
39424.106520564 : ('39424.1061926', 'R:39424.105717079')
39424.287974935 : ('39424.2834823', 'C:39424.276599586')
39424.288687064 : ('39424.2885214', 'R:39424.287501672')
39424.450589871 : ('39424.4502686', 'R:39424.448834831')
39424.699508215 : ('39424.6992554', 'R:39424.698894705')
39424.873315787 : ('39424.8630923', 'C:39424.862771303')
39424.875017187 : ('39424.8747878', 'R:39424.872897562')
39424.953560649 : ('39424.9532514', 'R:39424.951815388')
39425.034659284 : ('39425.0344405', 'R:39425.034110589')
39425.136796041 : ('39425.1266164', 'C:39425.126178919')
39425.138228402 : ('39425.1372573', 'R:39425.136317750')
39425.208788977 : ('39425.208554', 'R:39425.208220168')
39425.368160359 : ('39425.367893', 'R:39425.367563332')
39425.543795888 : ('39425.5335263', 'C:39425.533226818')
39425.546291833 : ('39425.5457297', 'R:39425.543353915')
39425.698567346 : ('39425.6966514', 'R:39425.695960210')
39425.860141886 : ('39425.85704', 'R:39425.854546825')
39426.044458183 : ('39426.0342411', 'C:39426.033870116')
39426.046494554 : ('39426.0459213', 'R:39426.044029621')
39426.205851967 : ('39426.2056419', 'R:39426.205204933')
39426.374875228 : ('39426.3746646', 'R:39426.374243000')
39426.480422327 : ('39426.4702455', 'C:39426.469802132')
39426.482667951 : ('39426.4824584', 'R:39426.479933699')
39426.549515062 : ('39426.549293', 'R:39426.548961339')
39426.631321635 : ('39426.6280622', '2a:39426.626464405')
39426.718553409 : ('39426.7182212', '*R:39426.717680359')
39426.894481165 : ('39426.8841445', 'C:39426.883769055')
39426.897186921 : ('39426.8956699', 'R:39426.893897549')
39427.041911183 : ('39427.0415776', 'R:39427.040222635')
39427.208230364 : ('39427.2078647', 'R:39427.200774100')
39427.381077442 : ('39427.3752983', 'C:39427.370004658')
39427.383596575 : ('39427.3834069', 'R:39427.380589932')
39427.447785424 : ('39427.4441267', 'R:39427.442588194')
39427.528748003 : ('39427.5284242', 'R:39427.528051519')
39427.622427214 : ('39427.6115388', 'C:39427.608574918')
39427.623961546 : ('39427.6229631', 'R:39427.621392126')
39427.690048754 : ('39427.6898051', 'R:39427.689439156')
39427.852274241 : ('39427.8519611', 'R:39427.851477181')
39428.023089418 : ('39428.0126226', 'C:39428.012149058')
39428.025804673 : ('39428.0236401', 'R:39428.022364996')
39428.185052850 : ('39428.1846346', 'R:39428.183845666')
39428.348834180 : ('39428.3485026', 'R:39428.341089601')
39428.514710271 : ('39428.504287', 'C:39428.503805671')
39428.520293040 : ('39428.5170573', 'R:39428.513971322')
39428.591369064 : ('39428.5911581', 'R:39428.590696047')
39428.663423462 : ('39428.6631916', 'R:39428.662854653')
39428.837411791 : ('39428.8269209', 'C:39428.826618103')
39428.840263661 : ('39428.838324', 'R:39428.836727041')
39428.996725622 : ('39428.9964921', 'R:39428.995950912')
39429.169236053 : ('39429.1690078', 'R:39429.168670875')
39429.349270356 : ('39429.3388086', 'C:39429.338506281')
39429.355833454 : ('39429.3513486', 'R:39429.348637290')
39429.505441207 : ('39429.5051761', 'R:39429.504603079')
```

Conclusion, `0.0 s` of precision.

**Pull request merged**
