### PR TITLE
Add bundle.bat

### PR DESCRIPTION
**Pull request by papr**

### CODE REVIEW

**Comment by willpatera** [comment]
@papr I would have to test this myself on a Windows bundling env VM and will not be able to do so until Tuesday at earliest. Perhaps @pointcontrols would be the better reviewer for this PR.

**Comment by pointcontrols** [comment]
@papr Maybe not hardcode 7zip path like that ?

**Comment by papr** [comment]
I agree, but without the full path, the command was not found. Not sure if one has to modify some PATH variables first...

**Comment by pointcontrols** [comment]
Yes. The 7zip dir needs to be added to the system path on each machine
where bundling is going to be done.

**Comment by papr** [comment]
Ok, I will make this change tomorrow.

**Pull request merged**
